### ISSUE TITLE
RunTimeException

### ISSUE THREAD

**Issue by aagp** [akexorcist/Android-RoundCornerProgressBar#56] opened 2016-09-27 15:17 UTC
Hi i'm getting this through Firebase Crash Console, this happens when i put my app in background (recent list) for a while and then open it again after i dont know several minutes, then app crashes, thanks to firebase i can see the error. This is what it shows:

Thanks in advance.

```
Exception java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ayc.ayc_app/com.ayc.ayc_app.HolderActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.akexorcist.roundcornerprogressbar.common.BaseRoundCornerProgressBar$SavedState
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2209)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2269)
android.app.ActivityThread.access$800 (ActivityThread.java:139)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1210)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:136)
android.app.ActivityThread.main (ActivityThread.java:5102)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:803)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:619)
dalvik.system.NativeStart.main (NativeStart.java)
arrow_drop_down
Caused by android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.akexorcist.roundcornerprogressbar.common.BaseRoundCornerProgressBar$SavedState
android.os.Parcel.readParcelableCreator (Parcel.java:2154)
android.os.Parcel.readParcelable (Parcel.java:2104)
android.view.AbsSavedState.<init> (AbsSavedState.java:57)
android.view.View$BaseSavedState.<init> (View.java:18779)
com.akexorcist.roundcornerprogressbar.TextRoundCornerProgressBar$SavedState.<init> (TextRoundCornerProgressBar.java:318)
com.akexorcist.roundcornerprogressbar.TextRoundCornerProgressBar$SavedState.<init> (TextRoundCornerProgressBar.java:306)
com.akexorcist.roundcornerprogressbar.TextRoundCornerProgressBar$SavedState$1.createFromParcel (TextRoundCornerProgressBar.java:340)
com.akexorcist.roundcornerprogressbar.TextRoundCornerProgressBar$SavedState$1.createFromParcel (TextRoundCornerProgressBar.java:338)
android.os.Parcel.readParcelable (Parcel.java:2111)
android.os.Parcel.readValue (Parcel.java:2020)
android.os.Parcel.readSparseArrayInternal (Parcel.java:2382)
android.os.Parcel.readSparseArray (Parcel.java:1742)
android.os.Parcel.readValue (Parcel.java:2077)
android.os.Parcel.readArrayMapInternal (Parcel.java:2321)
android.os.Bundle.unparcel (Bundle.java:249)
android.os.Bundle.getSparseParcelableArray (Bundle.java:1275)
android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:997)
android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1252)
android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1234)
android.support.v4.app.FragmentManagerImpl.dispatchCreate (FragmentManager.java:2041)
android.support.v4.app.Fragment.performCreate (Fragment.java:1964)
android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1029)
android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1252)
android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1234)
android.support.v4.app.FragmentManagerImpl.dispatchCreate (FragmentManager.java:2041)
android.support.v4.app.FragmentController.dispatchCreate (FragmentController.java:163)
android.support.v4.app.FragmentActivity.onCreate (FragmentActivity.java:331)
android.support.v7.app.AppCompatActivity.onCreate (AppCompatActivity.java:85)
com.ayc.ayc_app.HolderActivity.onCreate (HolderActivity.java:45)
android.app.Activity.performCreate (Activity.java:5248)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1110)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2173)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2269)
android.app.ActivityThread.access$800 (ActivityThread.java:139)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1210)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:136)
android.app.ActivityThread.main (ActivityThread.java:5102)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:803)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:619)
dalvik.system.NativeStart.main (NativeStart.java)
```

**Comment by prashantm8** [comment] 2018-03-21 16:22
facing same issue

**Comment by akexorcist** [comment] 2020-04-16 17:18
Duplicate of #57

**Closed as completed by akexorcist** 2020-04-16 17:18 UTC
